### ISSUE TITLE
new to this

### ISSUE THREAD

**Issue by aferg011** [flightaware/aeroapps#17]
I set my key just by changing your sample-env file to .env, left the POST_PORT and WEB_SERVER_PORT variables there - took me a while to figure out how to add a variable to a venv 

screenshot of the results of my docker-compose python pull python up

lots of documentation about 
* not being able to run executable
* "cgroup"
* failed to create shim task
* OCI runtime

hope that's enough info - help?

![Screenshot 2023-05-10 at 11 15 50](https://github.com/flightaware/aeroapps/assets/83029442/993b7f67-897e-425d-bbe8-ff70e2d47b6e)

**Comment by bovine** [comment]
I think the main problem is that the Docker image is for x64 and you're on an arm platform. You need to rebuild the docker images for your CPU type first.

**Comment by bovine** [comment]
Resolving since this is a user environment or invocation issue.

**Comment by aferg011** [comment]
Thanks! I tried building my own images with this command

docker compose --profile python up --build

and got this

<img width="1389" alt="Screenshot 2023-05-27 at 19 16 44" src="https://github.com/flightaware/aeroapps/assets/83029442/103494cd-7cdf-4fb6-b07e-b4c5cba65478">

**Comment by aferg011** [comment]
@bovine could you reopen?

**Comment by bovine** [comment]
I don't think that built the fids-frontend, which is in a separate repo. See https://github.com/flightaware/fids_frontend to download and build that separately.

Unfortunately, you are attempting to use these examples on a platform architecture that we have not built or tested on, so there will likely be rough edges and things you will need to figure out yourself. If you want the smoothest experience, you should try on an Intel/AMD system first.
